/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'black': '#000000',
      'blue': '#0A1B3D',
      "lightblue": "#E8F4FD",
      'lightgrey': '#AEC7E4',
      'navyblue': '#0A1B3D',
      'ative-navy': '#0A1B3D',
      'ative-blue': '#1E3A8A',
      'ative-light': '#E8F4FD',
      'ative-gray': '#64748B',
      'beach': '#8EA9C1',
      'circlebg' : "rgba(10, 27, 61, 0.1)",
      'darkblue' : '#0A1B3D',
      'offwhite' : 'rgba(255, 255, 255, 0.95);',
      'bordertop' : 'rgba(196, 196, 196, 0.5);',
      'blue-500' : '#0A1B3D',
      'darkgray' : '#64748B',
      'babyblue' : '#E8F4FD',
      'grey500': '#F1F5F9',
      'bluegray' : "#64748B",
      'bluegrey' : "#64748B",
      'midnightblue' : '#0A1B3D',
      'midblue' : '#1E3A8A',
      'bluebg' : "rgba(10, 27, 61, 0.05)",
      'border' : "rgba(100, 116, 139, 0.2)",
      'gold' : "#F59E0B"
    },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.25rem' }],
      base: ['1rem', { lineHeight: '1.5rem' }],
      lg: ['1.125rem', { lineHeight: '1.75rem' }],
      xl: ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      '5xl': ['3rem', { lineHeight: '1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
      '65xl': ['65px', { lineHeight: '1' }],
      '80xl': ['80px', { lineHeight: '6rem' }],
    },
    extend: {},
  },
  plugins: [],
}